
= Model
:description: View the list of object types supported in OpenNMS's Architecture for Learning Enabled Correlation (ALEC), that uses machine learning to group related alarms.

== Object types

The following object types are supported using built-in inventory scripts:

[cols="1,3"]
|===
| Type  | Description

| node
| Associates an alarm with a node object.
No parameters are required.

| snmp-interface
| Represents a physical or logical network device that is being monitored using SNMP.
Requires either the `ifIndex` or `ifDescr` parameter to be set. +
When an `ifIndex` value is passed, it is used as-is. +
When an `ifDescr` value is passed, {page-component-title} tries to look up the `ifIndex` with the matching `ifDescr` or `ifName` value on the node.

| [[snmp-interface-link]]snmp-interface-link
| Represents a logical link between two physical network interfaces on a device that is being monitored using SNMP.
Requires the `aIfDescr`, `zIfDescr`, and `zHostname` parameters to be set.

| bgp-peer
| Represents a BGP peer relationship between two monitored network devices.
Requires the `bgpPeer` parameters to be set.

| vpn-tunnel
| Represents a VPN tunnel between two monitored network devices.
Requires the `peerLocalAddr`, `peerRemoteAddr`, and `tunnelId` parameters to be set.

| mpls-l3-vrf
| Represents a VRF instance in a monitored MPLS network.
Requires either the `vrfNameOid` or `vrfName` parameter to be set.

| ent-physical-entity
| Represents a physical entity on a device that is being monitored using the Entity-MIB standard.
Requires the `entPhysicalIndex` parameter to be set.

| ospf-router
| Represents an OSPF router in a monitored network.
Requires the `ospfRouterId` parameter to be set.

| mpls-tunnel
| Represents an MPLS tunnel between two monitored network devices.
Requires the `mpls-tunnel` parameter to be set.

| mpls-ldp-session
| Represents an LDP session in a monitored MPLS network.
Requires the `mlplsLdpEntityId` parameter to be set.
|===
