:imagesdir: ../assets/images
= Model

== Types

The following types are supported using the built-in inventory scripts:

=== Node (node)

Associates the alarm with a node object.

There are no parameters required aside from the alarm being associated to a node.

=== SNMP interface (snmp-interface)

Requires the `ifIndex` or `ifDescr` parameters to be set.

When given an `ifIndex` it will be used as-is.

When given an `ifDescr` we will attempt to lookup the associated `ifIndex` with the matching `ifDescr` or `ifName` on the node.

[[snmp-interface-link]]
=== SNMP interface link (snmp-interface-link)

Requires the `aIfDescr`, `zIfDescr` and `zHostname` parameters to be set.

=== BGP peer (bgp-peer)

Requires the `bgpPeer` parameters to be set.

=== VPN tunnel (vpn-tunnel)

Requires the `peerLocalAddr`, `peerRemoteAddr` and `tunnelId` parameters to be set.

=== MPLS L3 VRF (mpls-l3-vrf)

Requires the `vrfNameOid` or `vrfName` parameter to be set.

=== Entity-MIB physical entity (ent-physical-entity)

Requires the `entPhysicalIndex` parameter to be set.

=== OSPF router (ospf-router)

Requires the `ospfRouterId` parameter to be set.

=== MPLS tunnel (mpls-tunnel)

Requires the `mpls-tunnel` parameter to be set.

=== MPLS LDP session (mpls-tunnel)

Requires the `mplsLdpEntityID` parameter to be set.
