package org.opennms.oce.drools.engine.sample;

import org.opennms.oce.connector.model.Alarm
import org.opennms.oce.connector.model.Card
import org.opennms.oce.connector.model.Device
import org.opennms.oce.connector.model.Port
import java.util.List

global org.opennms.oce.drools.engine.CardStateManager stateMgr

rule "CardDown"
when
    $card : Card(ports != null, ports.size > 0)
    List(size >= $card.ports.size * 0.6) from collect (Port(failed == true) from $card.ports)
then
    // Card has failed!
    stateMgr.fail($card);
end

rule "CardRecovered"
when
    $card : Card(ports != null, ports.size > 0)
    List(size < $card.ports.size * 0.6) from collect (Port(failed == true) from $card.ports)
then
    // Card has recovered!
    stateMgr.recover($card);
end
