site: 
  title: OpenNMS OCE Documentation
  url: https://oce.opennms.eu
  start_page: oce::index.adoc
content: 
  sources: 
  - url: https://github.com/OpenNMS/oce.git
    branches: HEAD
    tags: v*
    start_path: docs
ui:
  bundle:
    url: https://github.com/opennms-forge/antora-ui-opennms/releases/download/v1.0.0/ui-bundle.zip
  supplemental_files: supplemental-ui
asciidoc:
  attributes:
    stem: latexmath
output: 
  clean: true 
  dir: ./public 
  destinations: 
  - provider: fs
  - provider: archive 
