site: 
  title: OpenNMS ALEC Documentation
  url: https://alec.opennms.com
  start_page: alec::index.adoc
content: 
  sources: 
  - url: https://github.com/OpenNMS/alec.git
    branches: HEAD
    tags:
      - v*
      - '!v2.0.0.alpha0'
    start_path: docs
ui:
  bundle:
    url: https://github.com/opennms-forge/antora-ui-opennms/releases/download/v1.3.1/ui-bundle.zip
asciidoc:
  attributes:
    stem: latexmath
output: 
  clean: true 
  dir: ./public 
  destinations: 
  - provider: fs
  - provider: archive 
