site:
  title: OpenNMS ALEC Documentation
  url: https://alec.opennms.com
  start_page: alec::index.adoc
content:
  sources:
  - url: https://github.com/OpenNMS/alec.git
    branches: HEAD
    tags:
      - v*
      - '!v2.0.0.alpha0' # same SNAPSHOT version as another branch
      - '!v1.1.1' # Tag v1.1.1 has version number 1.1.1-SNAPSHOT use v1.1.1-doc instead
      - '!v1.1.1-rebuild' # I thought I needed to remake the debs, but I did not
    start_path: docs
ui:
  bundle:
    url: https://github.com/opennms-forge/antora-ui-opennms/releases/download/v3.1.0/ui-bundle.zip
asciidoc:
  attributes:
    stem: latexmath
    tabs: tabs
output:
  clean: true
  dir: ./public
  destinations:
  - provider: fs
  - provider: archive
