= Cluster Engine
:imagesdir: ../assets/images

== Overview

The cluster engine builds an in-memory graph that contains the inventory provided by the datasource.
Inventory objects are added to the graph as vertices and relationships among these objects are added as edges.
Alarms are then attached to the vertex for the inventory object they reference.

On every tick (which defaults to a 30 second interval), we run the DB-Scan algorithm against all of the alarms on the graph which outputs a a list of clusters of alarms.
These clusters are then mapped to situations which are forwarded back to the datasource.

== DB-Scan

The distance function used for the DB-Scan algorithm takes a weighted combination of both the distance in time and the distance in space.
For time we use the absolute value between the last event times of the alarms.
For space we use the *cost* of traveling from one alarm to the other via the shortest path on the graph.

== Performance

This algorithm performs well when there are less than 500 candidate alarms. Alarms are only considered to be candidates for correlation when they have been created and/or updated in the last 2 hours (configurable).
