= Cluster Engine
:imagesdir: ../assets/images

== Overview

The cluster engine builds an in-memory graph that contains the inventory provided by the datasource.
Inventory objects are added to the graph as vertices and relationships among these objects are added as edges.
Alarms are then attached to the vertex for the inventory object they reference.

On every tick (which defaults to a 30 second interval), we run a clustering algorithm against all of the alarms on the graph which outputs a list of clusters of alarms.
The engine takes care of mapping the clusters to situations and forwards these back to the datasource.

The cluster engine is a generic implemenation which is meant to be extended for use with different clustering algorithms.
This engine handles all the details of interfacing with the datasource and managing state, allowing implementors to easily extend the engine with novel clustering techniques.
<<<<<<< HEAD
=======
<<<<<<< HEAD
<<<<<<< HEAD
=======

== Building the graph

== Distance on the graph

== Mapping cluster results to situations
>>>>>>> fdd8931... WIP.
=======
>>>>>>> 90b3953... adsf
>>>>>>> 6f9473d... Moar docs.
