version: 2.1

executors:
  build-executor:
    docker:
      - image: opennms/build-env:1.0-b4
        environment:
          MAVEN_OPTS: -Xmx2g

  # Note: Need to investigate how we can use our own image and have it configured so we can run docker inside docker
  # rather than rely on the circleci machine VM
  smoke-test-executor:
    machine: true
    environment:
      MAVEN_OPTS: -Xmx3200m
      TESTCONTAINERS_RYUK_DISABLED: true
      KEEP_TMP_OVERLAY: true
      TEST_RECORDING_DIR: /tmp/test-recordings

  docs-executor:
    docker:
      - image: antora/antora:2.0.0

  netlify-cli-executor:
    docker:
      - image: opennms/netlify-cli:2.8.3-b1

  package-cloud-cli-executor:
    docker:
      - image: opennms/package-cloud-cli:0.3.05-b1

workflows:
  build-deploy:
    jobs:
      # Run build jobs for all branches and any tag
      - pre-build:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - pre-build
          filters:
            tags:
              only: /.*/
      - build-docs:
          requires:
            - pre-build
          filters:
            tags:
              only: /.*/
      - smoke-test:
          requires:
            - build

      # Run deploy jobs just on version tags and master branch
      - deploy-maven:
          requires:
            - smoke-test
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master
      - deploy-packages:
          requires:
            - smoke-test
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master
      - deploy-docs:
          requires:
            - build-docs
            - smoke-test
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master

jobs:
  pre-build:
    executor: build-executor
    steps:
      - checkout

      - persist_to_workspace:
          root: ~/
          paths:
            - project

  build:
    executor: build-executor
    steps:
      - attach_workspace:
          at: ~/

      - restore_cache:
          keys:
          - v4-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v4-dependencies-

      - run:
          name: Build
          command: |
            mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v4-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Run the tests
          command: |
            mvn test integration-test

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit

      - run:
          name: Gather artifacts
          command: |
            mkdir -p ~/dist/
            cp assembly/opennms-rpm/target/rpm/opennms-oce-plugin/RPMS/noarch/* ~/dist/
            cp assembly/sentinel-rpm/target/rpm/sentinel-oce-plugin/RPMS/noarch/* ~/dist/
            cp assembly/kar/target/opennms-oce-plugin.kar ~/dist/
          when: always

      - store_artifacts:
          path: ~/dist
          destination: dist

      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - dist/*.kar

  smoke-test:
    executor: smoke-test-executor

    steps:
      - attach_workspace:
          at: ~/

      # Link root user's m2 repo from the cache with our user's m2 repo (the circleci user)
      - run:
          name: Link maven repo with cache
          command: |
            sudo chmod 777 /root
            ln -s /root/.m2 ~/.m2

      - restore_cache:
          keys:
          # attempt to use the cache from the last smoke-test run
          - v2-smoke-dependencies-{{ checksum "smoke-test/pom.xml" }}-{{ checksum "pom.xml" }}
          # use the cache built for the same root pom
          - v4-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v4-dependencies-
          
      - restore_cache:
          keys:
          - v1-docker-{{ checksum "smoke-test/src/main/resources/docker_fixed_images" }}

      - run:
          name: Make the kar available
          command: |
            mkdir -p ~/assembly/kar/target/
            ln -s ~/dist/opennms-oce-plugin.kar ~/assembly/kar/target/opennms-oce-plugin.kar

      - run:
          name: Import docker images
          command: |
            if [ -z "$(ls /tmp/docker 2> /dev/null)" ]; then exit 0; fi
            source smoke-test/src/main/resources/docker_fixed_images
            for dockerTargz in $(ls /tmp/docker); do
              dockerName="${dockerTargz%.*}"
              echo "Importing ${!dockerName} from $dockerTargz"
              docker load --input /tmp/docker/"$dockerTargz"
            done
            docker image ls
  
      - run:
          name: Run the tests
          command: |
            mkdir $TEST_RECORDING_DIR
            cd smoke-test
            mvn test -DsmokeTest=true
            
      - save_cache:
          paths:
          - /root/.m2
          key: v2-smoke-dependencies-{{ checksum "smoke-test/pom.xml" }}-{{ checksum "pom.xml" }}

      - run:
          name: Save cacheable docker images
          command: |
            if [ -d /tmp/docker ]; then exit 0; fi
            mkdir /tmp/docker
            tagsFile="smoke-test/src/main/resources/docker_fixed_images"
            source "$tagsFile"
            for dockerImg in $(awk -F '=' '/^[^#]/ {print $1}' "$tagsFile"); do
              echo "Saving docker image ${!dockerImg} as ${dockerImg}.tgz"
              docker save -o /tmp/docker/"$dockerImg".tgz "${!dockerImg}"
            done

      - save_cache:
          paths:
          - /tmp/docker
          key: v1-docker-{{ checksum "smoke-test/src/main/resources/docker_fixed_images" }}
  
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
  
      - store_test_results:
          path: ~/junit

      - store_artifacts:
          path: ~/logs

      # Unfortunately I can't reference the env variable containing the recording path here so I have to
      # duplicate it
      - store_artifacts:
          path: /tmp/test-recordings

      # Future Improvements:
      # - Store the logs from the sentinel and OpenNMS containers for the test run in addition to the junit logs
      #   - Mount the logs directories from the containers so we can copy the logs out easier
      # - Add nightly test run back once tests are proven stable
      #   - We might want to test nightly against the floating (latest) images for opennms and sentinel

  build-docs:
    executor: docs-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Generate HTML output for documentation
          command: |
            antora generate site.yml

      - store_artifacts:
          path: build/site.zip
          destination: site.zip

      - persist_to_workspace:
          root: ~/
          paths:
            - project/public
            - project/build

  deploy-maven:
    executor: build-executor
    steps:
      - attach_workspace:
          at: ~/
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v4-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v4-dependencies-

      - run:
          name: Deploy the artifacts
          command: |
            mvn -s .circleci.settings.xml -DskipTests deploy

  deploy-packages:
      executor: package-cloud-cli-executor
      steps:
        - attach_workspace:
            at: ~/
        - run:
            name: Push RPM packages
            command: |
              package_cloud push opennms/plugin-snapshot/el/7 assembly/opennms-rpm/target/rpm/opennms-oce-plugin/RPMS/noarch/*
              package_cloud push opennms/plugin-snapshot/el/7 assembly/sentinel-rpm/target/rpm/sentinel-oce-plugin/RPMS/noarch/*
  
  deploy-docs:
    executor: netlify-cli-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Deploy docs to Netlify
          command: |
            netlify deploy --prod -d public -s ${NETLIFY_SITE_ID}
