
= Clustering Engine

The clustering engine is a xref:engines/introduction.adoc[correlation engine] that uses the https://en.wikipedia.org/wiki/DBSCAN[DBSCAN algorithm] to build alarm clusters.
It draws information from the locally persisted network inventory graph.
ALEC automatically creates and maintains this graph, which is based on information from the associated xref:datasources/overview.adoc[datasource].

== DBSCAN algorithm

The DBSCAN algorithm that forms the basis for the clustering engine measures the distance between alarms on the network inventory graph to determine whether they should be correlated into a cluster.
The distance function calculates a weighted combination of distance in both time and space (on the shortest possible path between affected nodes) between alarms.

== Hellinger distance

The clustering engine can use https://en.wikipedia.org/wiki/Hellinger_distance[Hellinger distance] calculations to more accurately render the distance between alarms.
The results of its calculations are used as scaling variables.
Alarms are pushed further apart if the value is high, and vice versa.

You can enable Hellinger distance calculations when you xref:quick-start:engine-config.adoc#clustering-engine-config[configure the clustering engine], or by updating your engine configuration settings:

. Click *Plugins > ALEC* in the top menu bar.
. Click the *gear* symbol in the top-right of the screen.
. Select *With Hellinger Distance*, and click *Save Changes*.

NOTE: You must be using the clustering engine to enable Hellinger distance calculations.

== Performance

The clustering engine performs well when fewer than 500 candidate alarms exist.
You can use the clustering engine on monitored networks that periodically experience more than 500 active alarms, since many of them will age out over time.
The ALEC plugin's performance may degrade when more than 500 active candidate alarms exist in your OpenNMS instance.

Note that ALEC considers only recent alarms (created or updated within the previous two hours) as candidates for correlation.
You can configure the interval that ALEC uses to determine which alarms are candidates for correlation.
