= User's Guide to ALEC
:page-layout: home
:!sectids:

Welcome to the Architecture for Learning Enabled Correlation (ALEC).
This guide provides information and procedures to understand and deploy advanced software concepts and components that make up ALEC.

First launched in 2019, we built ALEC after several years of research and development.
The developer community played a significant role vetting the machine learning algorithms and deep-learning technologies that best fit OpenNMS and best correlated problems detected by their OpenNMS management systems.

Now, in 2022, we have revisited ALEC to improve it:

* New UI for easier management and visualization of the alarms and situations ALEC presents.
* Situation timeline to visualize the time alarms started, for better root-cause analysis.
* Hellinger distance mechanism to detect which alarms are related.

The updated ALEC also includes the ability to opt in to share your anonymized data with The OpenNMS Group so that we can improve the machine-learning technology for more precise results.

This guide assumes that readers have a basic understanding of OpenNMS.

For an overview of ALEC, see xref:about:welcome.adoc[What is ALEC?]
