= User's Guide to ALEC
:!sectids:
:description: Get an overview of OpenNMS's Architecture for Learning Enabled Correlation (ALEC) that uses machine learning to logically group related alarms.

Welcome to the Architecture for Learning Enabled Correlation (ALEC).
This guide provides information and procedures to help you understand and deploy the advanced software concepts and components that make up ALEC.

First launched in 2019, we built ALEC after several years of research and development.
The developer community played a significant role vetting the machine learning algorithms and deep-learning technologies that best fit OpenNMS and best correlated problems detected by their OpenNMS management systems.

Now, in 2022, we have revisited ALEC to improve it:

* Updated the UI for easier management and visualization of alarms and situations.
* Added the situation timeline to visualize the lifecycle of a situation's alarms, for better root-cause analysis.
* Included the option to use Hellinger distance calculations with the clustering engine, to better detect relationships between alarms.

The updated ALEC also includes the ability to opt in to share your anonymized data with The OpenNMS Group so that we can improve the machine-learning technology for more precise results.

This guide assumes that readers have a basic understanding of OpenNMS.

For an overview of ALEC, see xref:about:welcome.adoc[What is ALEC?]
