/*******************************************************************************
 * This file is part of OpenNMS(R).
 *
 * Copyright (C) 2022 The OpenNMS Group, Inc.
 * OpenNMS(R) is Copyright (C) 1999-2022 The OpenNMS Group, Inc.
 *
 * OpenNMS(R) is a registered trademark of The OpenNMS Group, Inc.
 *
 * OpenNMS(R) is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * OpenNMS(R) is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with OpenNMS(R).  If not, see:
 *      http://www.gnu.org/licenses/
 *
 * For more information contact:
 *     OpenNMS(R) Licensing <license@opennms.org>
 *     http://www.opennms.org/
 *     http://www.opennms.com/
 *******************************************************************************/
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: situationset.proto

package org.opennms.alec.grpc;

public interface AlarmOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Alarm)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 alarm_id = 1;</code>
   * @return The alarmId.
   */
  long getAlarmId();

  /**
   * <code>.google.protobuf.Timestamp first_time_seen = 2;</code>
   * @return Whether the firstTimeSeen field is set.
   */
  boolean hasFirstTimeSeen();
  /**
   * <code>.google.protobuf.Timestamp first_time_seen = 2;</code>
   * @return The firstTimeSeen.
   */
  com.google.protobuf.Timestamp getFirstTimeSeen();
  /**
   * <code>.google.protobuf.Timestamp first_time_seen = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getFirstTimeSeenOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp last_time_seen = 3;</code>
   * @return Whether the lastTimeSeen field is set.
   */
  boolean hasLastTimeSeen();
  /**
   * <code>.google.protobuf.Timestamp last_time_seen = 3;</code>
   * @return The lastTimeSeen.
   */
  com.google.protobuf.Timestamp getLastTimeSeen();
  /**
   * <code>.google.protobuf.Timestamp last_time_seen = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getLastTimeSeenOrBuilder();

  /**
   * <code>string inventory_object_id = 4;</code>
   * @return The inventoryObjectId.
   */
  String getInventoryObjectId();
  /**
   * <code>string inventory_object_id = 4;</code>
   * @return The bytes for inventoryObjectId.
   */
  com.google.protobuf.ByteString
      getInventoryObjectIdBytes();

  /**
   * <code>string inventory_object_type = 5;</code>
   * @return The inventoryObjectType.
   */
  String getInventoryObjectType();
  /**
   * <code>string inventory_object_type = 5;</code>
   * @return The bytes for inventoryObjectType.
   */
  com.google.protobuf.ByteString
      getInventoryObjectTypeBytes();

  /**
   * <code>string severity = 6;</code>
   * @return The severity.
   */
  String getSeverity();
  /**
   * <code>string severity = 6;</code>
   * @return The bytes for severity.
   */
  com.google.protobuf.ByteString
      getSeverityBytes();

  /**
   * <code>string summary = 7;</code>
   * @return The summary.
   */
  String getSummary();
  /**
   * <code>string summary = 7;</code>
   * @return The bytes for summary.
   */
  com.google.protobuf.ByteString
      getSummaryBytes();

  /**
   * <code>string description = 8;</code>
   * @return The description.
   */
  String getDescription();
  /**
   * <code>string description = 8;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>repeated string tags = 9;</code>
   * @return A list containing the tags.
   */
  java.util.List<String>
      getTagsList();
  /**
   * <code>repeated string tags = 9;</code>
   * @return The count of tags.
   */
  int getTagsCount();
  /**
   * <code>repeated string tags = 9;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  String getTags(int index);
  /**
   * <code>repeated string tags = 9;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);
}
