/*******************************************************************************
 * This file is part of OpenNMS(R).
 *
 * Copyright (C) 2022 The OpenNMS Group, Inc.
 * OpenNMS(R) is Copyright (C) 1999-2022 The OpenNMS Group, Inc.
 *
 * OpenNMS(R) is a registered trademark of The OpenNMS Group, Inc.
 *
 * OpenNMS(R) is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * OpenNMS(R) is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with OpenNMS(R).  If not, see:
 *      http://www.gnu.org/licenses/
 *
 * For more information contact:
 *     OpenNMS(R) Licensing <license@opennms.org>
 *     http://www.opennms.org/
 *     http://www.opennms.com/
 *******************************************************************************/
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: situationset.proto

package org.opennms.alec.grpc;

/**
 * Protobuf type {@code Alarm}
 */
public final class Alarm extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Alarm)
    AlarmOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Alarm.newBuilder() to construct.
  private Alarm(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Alarm() {
    inventoryObjectId_ = "";
    inventoryObjectType_ = "";
    severity_ = "";
    summary_ = "";
    description_ = "";
    tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    salarmId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Alarm();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Alarm(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            alarmId_ = input.readInt64();
            break;
          }
          case 18: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (firstTimeSeen_ != null) {
              subBuilder = firstTimeSeen_.toBuilder();
            }
            firstTimeSeen_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(firstTimeSeen_);
              firstTimeSeen_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (lastTimeSeen_ != null) {
              subBuilder = lastTimeSeen_.toBuilder();
            }
            lastTimeSeen_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lastTimeSeen_);
              lastTimeSeen_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            inventoryObjectId_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            inventoryObjectType_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            severity_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            summary_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              tags_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            tags_.add(s);
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            salarmId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        tags_ = tags_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.opennms.alec.grpc.SituationSetProtos.internal_static_Alarm_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.opennms.alec.grpc.SituationSetProtos.internal_static_Alarm_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.opennms.alec.grpc.Alarm.class, org.opennms.alec.grpc.Alarm.Builder.class);
  }

  public static final int ALARM_ID_FIELD_NUMBER = 1;
  private long alarmId_;
  /**
   * <code>int64 alarm_id = 1;</code>
   * @return The alarmId.
   */
  @java.lang.Override
  public long getAlarmId() {
    return alarmId_;
  }

  public static final int FIRST_TIME_SEEN_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp firstTimeSeen_;
  /**
   * <code>.google.protobuf.Timestamp first_time_seen = 2;</code>
   * @return Whether the firstTimeSeen field is set.
   */
  @java.lang.Override
  public boolean hasFirstTimeSeen() {
    return firstTimeSeen_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp first_time_seen = 2;</code>
   * @return The firstTimeSeen.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getFirstTimeSeen() {
    return firstTimeSeen_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : firstTimeSeen_;
  }
  /**
   * <code>.google.protobuf.Timestamp first_time_seen = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getFirstTimeSeenOrBuilder() {
    return getFirstTimeSeen();
  }

  public static final int LAST_TIME_SEEN_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp lastTimeSeen_;
  /**
   * <code>.google.protobuf.Timestamp last_time_seen = 3;</code>
   * @return Whether the lastTimeSeen field is set.
   */
  @java.lang.Override
  public boolean hasLastTimeSeen() {
    return lastTimeSeen_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp last_time_seen = 3;</code>
   * @return The lastTimeSeen.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getLastTimeSeen() {
    return lastTimeSeen_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastTimeSeen_;
  }
  /**
   * <code>.google.protobuf.Timestamp last_time_seen = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getLastTimeSeenOrBuilder() {
    return getLastTimeSeen();
  }

  public static final int INVENTORY_OBJECT_ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object inventoryObjectId_;
  /**
   * <code>string inventory_object_id = 4;</code>
   * @return The inventoryObjectId.
   */
  @java.lang.Override
  public java.lang.String getInventoryObjectId() {
    java.lang.Object ref = inventoryObjectId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      inventoryObjectId_ = s;
      return s;
    }
  }
  /**
   * <code>string inventory_object_id = 4;</code>
   * @return The bytes for inventoryObjectId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInventoryObjectIdBytes() {
    java.lang.Object ref = inventoryObjectId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      inventoryObjectId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INVENTORY_OBJECT_TYPE_FIELD_NUMBER = 5;
  private volatile java.lang.Object inventoryObjectType_;
  /**
   * <code>string inventory_object_type = 5;</code>
   * @return The inventoryObjectType.
   */
  @java.lang.Override
  public java.lang.String getInventoryObjectType() {
    java.lang.Object ref = inventoryObjectType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      inventoryObjectType_ = s;
      return s;
    }
  }
  /**
   * <code>string inventory_object_type = 5;</code>
   * @return The bytes for inventoryObjectType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInventoryObjectTypeBytes() {
    java.lang.Object ref = inventoryObjectType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      inventoryObjectType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEVERITY_FIELD_NUMBER = 6;
  private volatile java.lang.Object severity_;
  /**
   * <code>string severity = 6;</code>
   * @return The severity.
   */
  @java.lang.Override
  public java.lang.String getSeverity() {
    java.lang.Object ref = severity_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      severity_ = s;
      return s;
    }
  }
  /**
   * <code>string severity = 6;</code>
   * @return The bytes for severity.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSeverityBytes() {
    java.lang.Object ref = severity_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      severity_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUMMARY_FIELD_NUMBER = 7;
  private volatile java.lang.Object summary_;
  /**
   * <code>string summary = 7;</code>
   * @return The summary.
   */
  @java.lang.Override
  public java.lang.String getSummary() {
    java.lang.Object ref = summary_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      summary_ = s;
      return s;
    }
  }
  /**
   * <code>string summary = 7;</code>
   * @return The bytes for summary.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSummaryBytes() {
    java.lang.Object ref = summary_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      summary_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 8;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 8;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 8;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TAGS_FIELD_NUMBER = 9;
  private com.google.protobuf.LazyStringList tags_;
  /**
   * <code>repeated string tags = 9;</code>
   * @return A list containing the tags.
   */
  public com.google.protobuf.ProtocolStringList
      getTagsList() {
    return tags_;
  }
  /**
   * <code>repeated string tags = 9;</code>
   * @return The count of tags.
   */
  public int getTagsCount() {
    return tags_.size();
  }
  /**
   * <code>repeated string tags = 9;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  public java.lang.String getTags(int index) {
    return tags_.get(index);
  }
  /**
   * <code>repeated string tags = 9;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  public com.google.protobuf.ByteString
      getTagsBytes(int index) {
    return tags_.getByteString(index);
  }

  public static final int SALARM_ID_FIELD_NUMBER = 10;
  private volatile java.lang.Object salarmId_;
  /**
   * <code>string salarm_id = 10;</code>
   * @return The salarmId.
   */
  @java.lang.Override
  public java.lang.String getSalarmId() {
    java.lang.Object ref = salarmId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      salarmId_ = s;
      return s;
    }
  }
  /**
   * <code>string salarm_id = 10;</code>
   * @return The bytes for salarmId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSalarmIdBytes() {
    java.lang.Object ref = salarmId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      salarmId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (alarmId_ != 0L) {
      output.writeInt64(1, alarmId_);
    }
    if (firstTimeSeen_ != null) {
      output.writeMessage(2, getFirstTimeSeen());
    }
    if (lastTimeSeen_ != null) {
      output.writeMessage(3, getLastTimeSeen());
    }
    if (!getInventoryObjectIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, inventoryObjectId_);
    }
    if (!getInventoryObjectTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, inventoryObjectType_);
    }
    if (!getSeverityBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, severity_);
    }
    if (!getSummaryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, summary_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, description_);
    }
    for (int i = 0; i < tags_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, tags_.getRaw(i));
    }
    if (!getSalarmIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, salarmId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (alarmId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, alarmId_);
    }
    if (firstTimeSeen_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getFirstTimeSeen());
    }
    if (lastTimeSeen_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getLastTimeSeen());
    }
    if (!getInventoryObjectIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, inventoryObjectId_);
    }
    if (!getInventoryObjectTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, inventoryObjectType_);
    }
    if (!getSeverityBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, severity_);
    }
    if (!getSummaryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, summary_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, description_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < tags_.size(); i++) {
        dataSize += computeStringSizeNoTag(tags_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTagsList().size();
    }
    if (!getSalarmIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, salarmId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.opennms.alec.grpc.Alarm)) {
      return super.equals(obj);
    }
    org.opennms.alec.grpc.Alarm other = (org.opennms.alec.grpc.Alarm) obj;

    if (getAlarmId()
        != other.getAlarmId()) return false;
    if (hasFirstTimeSeen() != other.hasFirstTimeSeen()) return false;
    if (hasFirstTimeSeen()) {
      if (!getFirstTimeSeen()
          .equals(other.getFirstTimeSeen())) return false;
    }
    if (hasLastTimeSeen() != other.hasLastTimeSeen()) return false;
    if (hasLastTimeSeen()) {
      if (!getLastTimeSeen()
          .equals(other.getLastTimeSeen())) return false;
    }
    if (!getInventoryObjectId()
        .equals(other.getInventoryObjectId())) return false;
    if (!getInventoryObjectType()
        .equals(other.getInventoryObjectType())) return false;
    if (!getSeverity()
        .equals(other.getSeverity())) return false;
    if (!getSummary()
        .equals(other.getSummary())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getTagsList()
        .equals(other.getTagsList())) return false;
    if (!getSalarmId()
        .equals(other.getSalarmId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ALARM_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAlarmId());
    if (hasFirstTimeSeen()) {
      hash = (37 * hash) + FIRST_TIME_SEEN_FIELD_NUMBER;
      hash = (53 * hash) + getFirstTimeSeen().hashCode();
    }
    if (hasLastTimeSeen()) {
      hash = (37 * hash) + LAST_TIME_SEEN_FIELD_NUMBER;
      hash = (53 * hash) + getLastTimeSeen().hashCode();
    }
    hash = (37 * hash) + INVENTORY_OBJECT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getInventoryObjectId().hashCode();
    hash = (37 * hash) + INVENTORY_OBJECT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getInventoryObjectType().hashCode();
    hash = (37 * hash) + SEVERITY_FIELD_NUMBER;
    hash = (53 * hash) + getSeverity().hashCode();
    hash = (37 * hash) + SUMMARY_FIELD_NUMBER;
    hash = (53 * hash) + getSummary().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    if (getTagsCount() > 0) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + getTagsList().hashCode();
    }
    hash = (37 * hash) + SALARM_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSalarmId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.opennms.alec.grpc.Alarm parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opennms.alec.grpc.Alarm parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opennms.alec.grpc.Alarm parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opennms.alec.grpc.Alarm parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opennms.alec.grpc.Alarm parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opennms.alec.grpc.Alarm parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opennms.alec.grpc.Alarm parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opennms.alec.grpc.Alarm parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.opennms.alec.grpc.Alarm parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.opennms.alec.grpc.Alarm parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.opennms.alec.grpc.Alarm parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opennms.alec.grpc.Alarm parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.opennms.alec.grpc.Alarm prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Alarm}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Alarm)
      org.opennms.alec.grpc.AlarmOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opennms.alec.grpc.SituationSetProtos.internal_static_Alarm_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opennms.alec.grpc.SituationSetProtos.internal_static_Alarm_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opennms.alec.grpc.Alarm.class, org.opennms.alec.grpc.Alarm.Builder.class);
    }

    // Construct using org.opennms.alec.grpc.Alarm.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      alarmId_ = 0L;

      if (firstTimeSeenBuilder_ == null) {
        firstTimeSeen_ = null;
      } else {
        firstTimeSeen_ = null;
        firstTimeSeenBuilder_ = null;
      }
      if (lastTimeSeenBuilder_ == null) {
        lastTimeSeen_ = null;
      } else {
        lastTimeSeen_ = null;
        lastTimeSeenBuilder_ = null;
      }
      inventoryObjectId_ = "";

      inventoryObjectType_ = "";

      severity_ = "";

      summary_ = "";

      description_ = "";

      tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      salarmId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.opennms.alec.grpc.SituationSetProtos.internal_static_Alarm_descriptor;
    }

    @java.lang.Override
    public org.opennms.alec.grpc.Alarm getDefaultInstanceForType() {
      return org.opennms.alec.grpc.Alarm.getDefaultInstance();
    }

    @java.lang.Override
    public org.opennms.alec.grpc.Alarm build() {
      org.opennms.alec.grpc.Alarm result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.opennms.alec.grpc.Alarm buildPartial() {
      org.opennms.alec.grpc.Alarm result = new org.opennms.alec.grpc.Alarm(this);
      int from_bitField0_ = bitField0_;
      result.alarmId_ = alarmId_;
      if (firstTimeSeenBuilder_ == null) {
        result.firstTimeSeen_ = firstTimeSeen_;
      } else {
        result.firstTimeSeen_ = firstTimeSeenBuilder_.build();
      }
      if (lastTimeSeenBuilder_ == null) {
        result.lastTimeSeen_ = lastTimeSeen_;
      } else {
        result.lastTimeSeen_ = lastTimeSeenBuilder_.build();
      }
      result.inventoryObjectId_ = inventoryObjectId_;
      result.inventoryObjectType_ = inventoryObjectType_;
      result.severity_ = severity_;
      result.summary_ = summary_;
      result.description_ = description_;
      if (((bitField0_ & 0x00000001) != 0)) {
        tags_ = tags_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.tags_ = tags_;
      result.salarmId_ = salarmId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.opennms.alec.grpc.Alarm) {
        return mergeFrom((org.opennms.alec.grpc.Alarm)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.opennms.alec.grpc.Alarm other) {
      if (other == org.opennms.alec.grpc.Alarm.getDefaultInstance()) return this;
      if (other.getAlarmId() != 0L) {
        setAlarmId(other.getAlarmId());
      }
      if (other.hasFirstTimeSeen()) {
        mergeFirstTimeSeen(other.getFirstTimeSeen());
      }
      if (other.hasLastTimeSeen()) {
        mergeLastTimeSeen(other.getLastTimeSeen());
      }
      if (!other.getInventoryObjectId().isEmpty()) {
        inventoryObjectId_ = other.inventoryObjectId_;
        onChanged();
      }
      if (!other.getInventoryObjectType().isEmpty()) {
        inventoryObjectType_ = other.inventoryObjectType_;
        onChanged();
      }
      if (!other.getSeverity().isEmpty()) {
        severity_ = other.severity_;
        onChanged();
      }
      if (!other.getSummary().isEmpty()) {
        summary_ = other.summary_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.tags_.isEmpty()) {
        if (tags_.isEmpty()) {
          tags_ = other.tags_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureTagsIsMutable();
          tags_.addAll(other.tags_);
        }
        onChanged();
      }
      if (!other.getSalarmId().isEmpty()) {
        salarmId_ = other.salarmId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.opennms.alec.grpc.Alarm parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.opennms.alec.grpc.Alarm) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long alarmId_ ;
    /**
     * <code>int64 alarm_id = 1;</code>
     * @return The alarmId.
     */
    @java.lang.Override
    public long getAlarmId() {
      return alarmId_;
    }
    /**
     * <code>int64 alarm_id = 1;</code>
     * @param value The alarmId to set.
     * @return This builder for chaining.
     */
    public Builder setAlarmId(long value) {
      
      alarmId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 alarm_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlarmId() {
      
      alarmId_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp firstTimeSeen_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> firstTimeSeenBuilder_;
    /**
     * <code>.google.protobuf.Timestamp first_time_seen = 2;</code>
     * @return Whether the firstTimeSeen field is set.
     */
    public boolean hasFirstTimeSeen() {
      return firstTimeSeenBuilder_ != null || firstTimeSeen_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp first_time_seen = 2;</code>
     * @return The firstTimeSeen.
     */
    public com.google.protobuf.Timestamp getFirstTimeSeen() {
      if (firstTimeSeenBuilder_ == null) {
        return firstTimeSeen_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : firstTimeSeen_;
      } else {
        return firstTimeSeenBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp first_time_seen = 2;</code>
     */
    public Builder setFirstTimeSeen(com.google.protobuf.Timestamp value) {
      if (firstTimeSeenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        firstTimeSeen_ = value;
        onChanged();
      } else {
        firstTimeSeenBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp first_time_seen = 2;</code>
     */
    public Builder setFirstTimeSeen(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (firstTimeSeenBuilder_ == null) {
        firstTimeSeen_ = builderForValue.build();
        onChanged();
      } else {
        firstTimeSeenBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp first_time_seen = 2;</code>
     */
    public Builder mergeFirstTimeSeen(com.google.protobuf.Timestamp value) {
      if (firstTimeSeenBuilder_ == null) {
        if (firstTimeSeen_ != null) {
          firstTimeSeen_ =
            com.google.protobuf.Timestamp.newBuilder(firstTimeSeen_).mergeFrom(value).buildPartial();
        } else {
          firstTimeSeen_ = value;
        }
        onChanged();
      } else {
        firstTimeSeenBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp first_time_seen = 2;</code>
     */
    public Builder clearFirstTimeSeen() {
      if (firstTimeSeenBuilder_ == null) {
        firstTimeSeen_ = null;
        onChanged();
      } else {
        firstTimeSeen_ = null;
        firstTimeSeenBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp first_time_seen = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getFirstTimeSeenBuilder() {
      
      onChanged();
      return getFirstTimeSeenFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp first_time_seen = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getFirstTimeSeenOrBuilder() {
      if (firstTimeSeenBuilder_ != null) {
        return firstTimeSeenBuilder_.getMessageOrBuilder();
      } else {
        return firstTimeSeen_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : firstTimeSeen_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp first_time_seen = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getFirstTimeSeenFieldBuilder() {
      if (firstTimeSeenBuilder_ == null) {
        firstTimeSeenBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getFirstTimeSeen(),
                getParentForChildren(),
                isClean());
        firstTimeSeen_ = null;
      }
      return firstTimeSeenBuilder_;
    }

    private com.google.protobuf.Timestamp lastTimeSeen_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastTimeSeenBuilder_;
    /**
     * <code>.google.protobuf.Timestamp last_time_seen = 3;</code>
     * @return Whether the lastTimeSeen field is set.
     */
    public boolean hasLastTimeSeen() {
      return lastTimeSeenBuilder_ != null || lastTimeSeen_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp last_time_seen = 3;</code>
     * @return The lastTimeSeen.
     */
    public com.google.protobuf.Timestamp getLastTimeSeen() {
      if (lastTimeSeenBuilder_ == null) {
        return lastTimeSeen_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastTimeSeen_;
      } else {
        return lastTimeSeenBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp last_time_seen = 3;</code>
     */
    public Builder setLastTimeSeen(com.google.protobuf.Timestamp value) {
      if (lastTimeSeenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastTimeSeen_ = value;
        onChanged();
      } else {
        lastTimeSeenBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_time_seen = 3;</code>
     */
    public Builder setLastTimeSeen(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (lastTimeSeenBuilder_ == null) {
        lastTimeSeen_ = builderForValue.build();
        onChanged();
      } else {
        lastTimeSeenBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_time_seen = 3;</code>
     */
    public Builder mergeLastTimeSeen(com.google.protobuf.Timestamp value) {
      if (lastTimeSeenBuilder_ == null) {
        if (lastTimeSeen_ != null) {
          lastTimeSeen_ =
            com.google.protobuf.Timestamp.newBuilder(lastTimeSeen_).mergeFrom(value).buildPartial();
        } else {
          lastTimeSeen_ = value;
        }
        onChanged();
      } else {
        lastTimeSeenBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_time_seen = 3;</code>
     */
    public Builder clearLastTimeSeen() {
      if (lastTimeSeenBuilder_ == null) {
        lastTimeSeen_ = null;
        onChanged();
      } else {
        lastTimeSeen_ = null;
        lastTimeSeenBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_time_seen = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getLastTimeSeenBuilder() {
      
      onChanged();
      return getLastTimeSeenFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp last_time_seen = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getLastTimeSeenOrBuilder() {
      if (lastTimeSeenBuilder_ != null) {
        return lastTimeSeenBuilder_.getMessageOrBuilder();
      } else {
        return lastTimeSeen_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : lastTimeSeen_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp last_time_seen = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getLastTimeSeenFieldBuilder() {
      if (lastTimeSeenBuilder_ == null) {
        lastTimeSeenBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getLastTimeSeen(),
                getParentForChildren(),
                isClean());
        lastTimeSeen_ = null;
      }
      return lastTimeSeenBuilder_;
    }

    private java.lang.Object inventoryObjectId_ = "";
    /**
     * <code>string inventory_object_id = 4;</code>
     * @return The inventoryObjectId.
     */
    public java.lang.String getInventoryObjectId() {
      java.lang.Object ref = inventoryObjectId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        inventoryObjectId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string inventory_object_id = 4;</code>
     * @return The bytes for inventoryObjectId.
     */
    public com.google.protobuf.ByteString
        getInventoryObjectIdBytes() {
      java.lang.Object ref = inventoryObjectId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        inventoryObjectId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string inventory_object_id = 4;</code>
     * @param value The inventoryObjectId to set.
     * @return This builder for chaining.
     */
    public Builder setInventoryObjectId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      inventoryObjectId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string inventory_object_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearInventoryObjectId() {
      
      inventoryObjectId_ = getDefaultInstance().getInventoryObjectId();
      onChanged();
      return this;
    }
    /**
     * <code>string inventory_object_id = 4;</code>
     * @param value The bytes for inventoryObjectId to set.
     * @return This builder for chaining.
     */
    public Builder setInventoryObjectIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      inventoryObjectId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object inventoryObjectType_ = "";
    /**
     * <code>string inventory_object_type = 5;</code>
     * @return The inventoryObjectType.
     */
    public java.lang.String getInventoryObjectType() {
      java.lang.Object ref = inventoryObjectType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        inventoryObjectType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string inventory_object_type = 5;</code>
     * @return The bytes for inventoryObjectType.
     */
    public com.google.protobuf.ByteString
        getInventoryObjectTypeBytes() {
      java.lang.Object ref = inventoryObjectType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        inventoryObjectType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string inventory_object_type = 5;</code>
     * @param value The inventoryObjectType to set.
     * @return This builder for chaining.
     */
    public Builder setInventoryObjectType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      inventoryObjectType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string inventory_object_type = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearInventoryObjectType() {
      
      inventoryObjectType_ = getDefaultInstance().getInventoryObjectType();
      onChanged();
      return this;
    }
    /**
     * <code>string inventory_object_type = 5;</code>
     * @param value The bytes for inventoryObjectType to set.
     * @return This builder for chaining.
     */
    public Builder setInventoryObjectTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      inventoryObjectType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object severity_ = "";
    /**
     * <code>string severity = 6;</code>
     * @return The severity.
     */
    public java.lang.String getSeverity() {
      java.lang.Object ref = severity_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        severity_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string severity = 6;</code>
     * @return The bytes for severity.
     */
    public com.google.protobuf.ByteString
        getSeverityBytes() {
      java.lang.Object ref = severity_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        severity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string severity = 6;</code>
     * @param value The severity to set.
     * @return This builder for chaining.
     */
    public Builder setSeverity(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      severity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string severity = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeverity() {
      
      severity_ = getDefaultInstance().getSeverity();
      onChanged();
      return this;
    }
    /**
     * <code>string severity = 6;</code>
     * @param value The bytes for severity to set.
     * @return This builder for chaining.
     */
    public Builder setSeverityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      severity_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object summary_ = "";
    /**
     * <code>string summary = 7;</code>
     * @return The summary.
     */
    public java.lang.String getSummary() {
      java.lang.Object ref = summary_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        summary_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string summary = 7;</code>
     * @return The bytes for summary.
     */
    public com.google.protobuf.ByteString
        getSummaryBytes() {
      java.lang.Object ref = summary_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        summary_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string summary = 7;</code>
     * @param value The summary to set.
     * @return This builder for chaining.
     */
    public Builder setSummary(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      summary_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string summary = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSummary() {
      
      summary_ = getDefaultInstance().getSummary();
      onChanged();
      return this;
    }
    /**
     * <code>string summary = 7;</code>
     * @param value The bytes for summary to set.
     * @return This builder for chaining.
     */
    public Builder setSummaryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      summary_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 8;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 8;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 8;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 8;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTagsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        tags_ = new com.google.protobuf.LazyStringArrayList(tags_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string tags = 9;</code>
     * @return A list containing the tags.
     */
    public com.google.protobuf.ProtocolStringList
        getTagsList() {
      return tags_.getUnmodifiableView();
    }
    /**
     * <code>repeated string tags = 9;</code>
     * @return The count of tags.
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <code>repeated string tags = 9;</code>
     * @param index The index of the element to return.
     * @return The tags at the given index.
     */
    public java.lang.String getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <code>repeated string tags = 9;</code>
     * @param index The index of the value to return.
     * @return The bytes of the tags at the given index.
     */
    public com.google.protobuf.ByteString
        getTagsBytes(int index) {
      return tags_.getByteString(index);
    }
    /**
     * <code>repeated string tags = 9;</code>
     * @param index The index to set the value at.
     * @param value The tags to set.
     * @return This builder for chaining.
     */
    public Builder setTags(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
      tags_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tags = 9;</code>
     * @param value The tags to add.
     * @return This builder for chaining.
     */
    public Builder addTags(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
      tags_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tags = 9;</code>
     * @param values The tags to add.
     * @return This builder for chaining.
     */
    public Builder addAllTags(
        java.lang.Iterable<java.lang.String> values) {
      ensureTagsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tags_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tags = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTags() {
      tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tags = 9;</code>
     * @param value The bytes of the tags to add.
     * @return This builder for chaining.
     */
    public Builder addTagsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureTagsIsMutable();
      tags_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object salarmId_ = "";
    /**
     * <code>string salarm_id = 10;</code>
     * @return The salarmId.
     */
    public java.lang.String getSalarmId() {
      java.lang.Object ref = salarmId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        salarmId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string salarm_id = 10;</code>
     * @return The bytes for salarmId.
     */
    public com.google.protobuf.ByteString
        getSalarmIdBytes() {
      java.lang.Object ref = salarmId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        salarmId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string salarm_id = 10;</code>
     * @param value The salarmId to set.
     * @return This builder for chaining.
     */
    public Builder setSalarmId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      salarmId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string salarm_id = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearSalarmId() {
      
      salarmId_ = getDefaultInstance().getSalarmId();
      onChanged();
      return this;
    }
    /**
     * <code>string salarm_id = 10;</code>
     * @param value The bytes for salarmId to set.
     * @return This builder for chaining.
     */
    public Builder setSalarmIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      salarmId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Alarm)
  }

  // @@protoc_insertion_point(class_scope:Alarm)
  private static final org.opennms.alec.grpc.Alarm DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.opennms.alec.grpc.Alarm();
  }

  public static org.opennms.alec.grpc.Alarm getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Alarm>
      PARSER = new com.google.protobuf.AbstractParser<Alarm>() {
    @java.lang.Override
    public Alarm parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Alarm(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Alarm> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Alarm> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.opennms.alec.grpc.Alarm getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

