/*******************************************************************************
 * This file is part of OpenNMS(R).
 *
 * Copyright (C) 2022 The OpenNMS Group, Inc.
 * OpenNMS(R) is Copyright (C) 1999-2022 The OpenNMS Group, Inc.
 *
 * OpenNMS(R) is a registered trademark of The OpenNMS Group, Inc.
 *
 * OpenNMS(R) is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * OpenNMS(R) is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with OpenNMS(R).  If not, see:
 *      http://www.gnu.org/licenses/
 *
 * For more information contact:
 *     OpenNMS(R) Licensing <license@opennms.org>
 *     http://www.opennms.org/
 *     http://www.opennms.com/
 *******************************************************************************/
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: situationset.proto

package org.opennms.alec.grpc;

/**
 * Protobuf type {@code Situation}
 */
public final class Situation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Situation)
    SituationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Situation.newBuilder() to construct.
  private Situation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Situation() {
    severity_ = "";
    diagnostic_ = "";
    tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    engineParameter_ = "";
    status_ = "";
    rejected_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Situation();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Situation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (creationTime_ != null) {
              subBuilder = creationTime_.toBuilder();
            }
            creationTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(creationTime_);
              creationTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            AlarmSet.Builder subBuilder = null;
            if (alarms_ != null) {
              subBuilder = alarms_.toBuilder();
            }
            alarms_ = input.readMessage(AlarmSet.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(alarms_);
              alarms_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            severity_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            diagnostic_ = s;
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              tags_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            tags_.add(s);
            break;
          }
          case 58: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (lastModificationTime_ != null) {
              subBuilder = lastModificationTime_.toBuilder();
            }
            lastModificationTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lastModificationTime_);
              lastModificationTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            String s = input.readStringRequireUtf8();

            engineParameter_ = s;
            break;
          }
          case 74: {
            String s = input.readStringRequireUtf8();

            status_ = s;
            break;
          }
          case 82: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              rejected_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            rejected_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        tags_ = tags_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        rejected_ = rejected_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return SituationSetProtos.internal_static_Situation_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return SituationSetProtos.internal_static_Situation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Situation.class, Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @Override
  public long getId() {
    return id_;
  }

  public static final int CREATION_TIME_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp creationTime_;
  /**
   * <code>.google.protobuf.Timestamp creation_time = 2;</code>
   * @return Whether the creationTime field is set.
   */
  @Override
  public boolean hasCreationTime() {
    return creationTime_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp creation_time = 2;</code>
   * @return The creationTime.
   */
  @Override
  public com.google.protobuf.Timestamp getCreationTime() {
    return creationTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : creationTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp creation_time = 2;</code>
   */
  @Override
  public com.google.protobuf.TimestampOrBuilder getCreationTimeOrBuilder() {
    return getCreationTime();
  }

  public static final int ALARMS_FIELD_NUMBER = 3;
  private AlarmSet alarms_;
  /**
   * <code>.AlarmSet alarms = 3;</code>
   * @return Whether the alarms field is set.
   */
  @Override
  public boolean hasAlarms() {
    return alarms_ != null;
  }
  /**
   * <code>.AlarmSet alarms = 3;</code>
   * @return The alarms.
   */
  @Override
  public AlarmSet getAlarms() {
    return alarms_ == null ? AlarmSet.getDefaultInstance() : alarms_;
  }
  /**
   * <code>.AlarmSet alarms = 3;</code>
   */
  @Override
  public AlarmSetOrBuilder getAlarmsOrBuilder() {
    return getAlarms();
  }

  public static final int SEVERITY_FIELD_NUMBER = 4;
  private volatile Object severity_;
  /**
   * <code>string severity = 4;</code>
   * @return The severity.
   */
  @Override
  public String getSeverity() {
    Object ref = severity_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      severity_ = s;
      return s;
    }
  }
  /**
   * <code>string severity = 4;</code>
   * @return The bytes for severity.
   */
  @Override
  public com.google.protobuf.ByteString
      getSeverityBytes() {
    Object ref = severity_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      severity_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIAGNOSTIC_FIELD_NUMBER = 5;
  private volatile Object diagnostic_;
  /**
   * <code>string diagnostic = 5;</code>
   * @return The diagnostic.
   */
  @Override
  public String getDiagnostic() {
    Object ref = diagnostic_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      diagnostic_ = s;
      return s;
    }
  }
  /**
   * <code>string diagnostic = 5;</code>
   * @return The bytes for diagnostic.
   */
  @Override
  public com.google.protobuf.ByteString
      getDiagnosticBytes() {
    Object ref = diagnostic_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      diagnostic_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TAGS_FIELD_NUMBER = 6;
  private com.google.protobuf.LazyStringList tags_;
  /**
   * <code>repeated string tags = 6;</code>
   * @return A list containing the tags.
   */
  public com.google.protobuf.ProtocolStringList
      getTagsList() {
    return tags_;
  }
  /**
   * <code>repeated string tags = 6;</code>
   * @return The count of tags.
   */
  public int getTagsCount() {
    return tags_.size();
  }
  /**
   * <code>repeated string tags = 6;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  public String getTags(int index) {
    return tags_.get(index);
  }
  /**
   * <code>repeated string tags = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  public com.google.protobuf.ByteString
      getTagsBytes(int index) {
    return tags_.getByteString(index);
  }

  public static final int LAST_MODIFICATION_TIME_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp lastModificationTime_;
  /**
   * <code>.google.protobuf.Timestamp last_modification_time = 7;</code>
   * @return Whether the lastModificationTime field is set.
   */
  @Override
  public boolean hasLastModificationTime() {
    return lastModificationTime_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp last_modification_time = 7;</code>
   * @return The lastModificationTime.
   */
  @Override
  public com.google.protobuf.Timestamp getLastModificationTime() {
    return lastModificationTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastModificationTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp last_modification_time = 7;</code>
   */
  @Override
  public com.google.protobuf.TimestampOrBuilder getLastModificationTimeOrBuilder() {
    return getLastModificationTime();
  }

  public static final int ENGINE_PARAMETER_FIELD_NUMBER = 8;
  private volatile Object engineParameter_;
  /**
   * <code>string engine_parameter = 8;</code>
   * @return The engineParameter.
   */
  @Override
  public String getEngineParameter() {
    Object ref = engineParameter_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      engineParameter_ = s;
      return s;
    }
  }
  /**
   * <code>string engine_parameter = 8;</code>
   * @return The bytes for engineParameter.
   */
  @Override
  public com.google.protobuf.ByteString
      getEngineParameterBytes() {
    Object ref = engineParameter_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      engineParameter_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 9;
  private volatile Object status_;
  /**
   * <code>string status = 9;</code>
   * @return The status.
   */
  @Override
  public String getStatus() {
    Object ref = status_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 9;</code>
   * @return The bytes for status.
   */
  @Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    Object ref = status_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REJECTED_FIELD_NUMBER = 10;
  private com.google.protobuf.LazyStringList rejected_;
  /**
   * <code>repeated string rejected = 10;</code>
   * @return A list containing the rejected.
   */
  public com.google.protobuf.ProtocolStringList
      getRejectedList() {
    return rejected_;
  }
  /**
   * <code>repeated string rejected = 10;</code>
   * @return The count of rejected.
   */
  public int getRejectedCount() {
    return rejected_.size();
  }
  /**
   * <code>repeated string rejected = 10;</code>
   * @param index The index of the element to return.
   * @return The rejected at the given index.
   */
  public String getRejected(int index) {
    return rejected_.get(index);
  }
  /**
   * <code>repeated string rejected = 10;</code>
   * @param index The index of the value to return.
   * @return The bytes of the rejected at the given index.
   */
  public com.google.protobuf.ByteString
      getRejectedBytes(int index) {
    return rejected_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (creationTime_ != null) {
      output.writeMessage(2, getCreationTime());
    }
    if (alarms_ != null) {
      output.writeMessage(3, getAlarms());
    }
    if (!getSeverityBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, severity_);
    }
    if (!getDiagnosticBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, diagnostic_);
    }
    for (int i = 0; i < tags_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, tags_.getRaw(i));
    }
    if (lastModificationTime_ != null) {
      output.writeMessage(7, getLastModificationTime());
    }
    if (!getEngineParameterBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, engineParameter_);
    }
    if (!getStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, status_);
    }
    for (int i = 0; i < rejected_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, rejected_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (creationTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCreationTime());
    }
    if (alarms_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getAlarms());
    }
    if (!getSeverityBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, severity_);
    }
    if (!getDiagnosticBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, diagnostic_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < tags_.size(); i++) {
        dataSize += computeStringSizeNoTag(tags_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTagsList().size();
    }
    if (lastModificationTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getLastModificationTime());
    }
    if (!getEngineParameterBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, engineParameter_);
    }
    if (!getStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, status_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < rejected_.size(); i++) {
        dataSize += computeStringSizeNoTag(rejected_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getRejectedList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Situation)) {
      return super.equals(obj);
    }
    Situation other = (Situation) obj;

    if (getId()
        != other.getId()) return false;
    if (hasCreationTime() != other.hasCreationTime()) return false;
    if (hasCreationTime()) {
      if (!getCreationTime()
          .equals(other.getCreationTime())) return false;
    }
    if (hasAlarms() != other.hasAlarms()) return false;
    if (hasAlarms()) {
      if (!getAlarms()
          .equals(other.getAlarms())) return false;
    }
    if (!getSeverity()
        .equals(other.getSeverity())) return false;
    if (!getDiagnostic()
        .equals(other.getDiagnostic())) return false;
    if (!getTagsList()
        .equals(other.getTagsList())) return false;
    if (hasLastModificationTime() != other.hasLastModificationTime()) return false;
    if (hasLastModificationTime()) {
      if (!getLastModificationTime()
          .equals(other.getLastModificationTime())) return false;
    }
    if (!getEngineParameter()
        .equals(other.getEngineParameter())) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (!getRejectedList()
        .equals(other.getRejectedList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    if (hasCreationTime()) {
      hash = (37 * hash) + CREATION_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getCreationTime().hashCode();
    }
    if (hasAlarms()) {
      hash = (37 * hash) + ALARMS_FIELD_NUMBER;
      hash = (53 * hash) + getAlarms().hashCode();
    }
    hash = (37 * hash) + SEVERITY_FIELD_NUMBER;
    hash = (53 * hash) + getSeverity().hashCode();
    hash = (37 * hash) + DIAGNOSTIC_FIELD_NUMBER;
    hash = (53 * hash) + getDiagnostic().hashCode();
    if (getTagsCount() > 0) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + getTagsList().hashCode();
    }
    if (hasLastModificationTime()) {
      hash = (37 * hash) + LAST_MODIFICATION_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getLastModificationTime().hashCode();
    }
    hash = (37 * hash) + ENGINE_PARAMETER_FIELD_NUMBER;
    hash = (53 * hash) + getEngineParameter().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    if (getRejectedCount() > 0) {
      hash = (37 * hash) + REJECTED_FIELD_NUMBER;
      hash = (53 * hash) + getRejectedList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Situation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Situation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Situation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Situation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Situation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Situation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Situation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Situation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Situation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Situation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Situation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Situation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Situation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Situation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Situation)
      SituationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SituationSetProtos.internal_static_Situation_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SituationSetProtos.internal_static_Situation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Situation.class, Builder.class);
    }

    // Construct using org.opennms.alec.grpc.Situation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      if (creationTimeBuilder_ == null) {
        creationTime_ = null;
      } else {
        creationTime_ = null;
        creationTimeBuilder_ = null;
      }
      if (alarmsBuilder_ == null) {
        alarms_ = null;
      } else {
        alarms_ = null;
        alarmsBuilder_ = null;
      }
      severity_ = "";

      diagnostic_ = "";

      tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (lastModificationTimeBuilder_ == null) {
        lastModificationTime_ = null;
      } else {
        lastModificationTime_ = null;
        lastModificationTimeBuilder_ = null;
      }
      engineParameter_ = "";

      status_ = "";

      rejected_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return SituationSetProtos.internal_static_Situation_descriptor;
    }

    @Override
    public Situation getDefaultInstanceForType() {
      return Situation.getDefaultInstance();
    }

    @Override
    public Situation build() {
      Situation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Situation buildPartial() {
      Situation result = new Situation(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      if (creationTimeBuilder_ == null) {
        result.creationTime_ = creationTime_;
      } else {
        result.creationTime_ = creationTimeBuilder_.build();
      }
      if (alarmsBuilder_ == null) {
        result.alarms_ = alarms_;
      } else {
        result.alarms_ = alarmsBuilder_.build();
      }
      result.severity_ = severity_;
      result.diagnostic_ = diagnostic_;
      if (((bitField0_ & 0x00000001) != 0)) {
        tags_ = tags_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.tags_ = tags_;
      if (lastModificationTimeBuilder_ == null) {
        result.lastModificationTime_ = lastModificationTime_;
      } else {
        result.lastModificationTime_ = lastModificationTimeBuilder_.build();
      }
      result.engineParameter_ = engineParameter_;
      result.status_ = status_;
      if (((bitField0_ & 0x00000002) != 0)) {
        rejected_ = rejected_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.rejected_ = rejected_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Situation) {
        return mergeFrom((Situation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Situation other) {
      if (other == Situation.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.hasCreationTime()) {
        mergeCreationTime(other.getCreationTime());
      }
      if (other.hasAlarms()) {
        mergeAlarms(other.getAlarms());
      }
      if (!other.getSeverity().isEmpty()) {
        severity_ = other.severity_;
        onChanged();
      }
      if (!other.getDiagnostic().isEmpty()) {
        diagnostic_ = other.diagnostic_;
        onChanged();
      }
      if (!other.tags_.isEmpty()) {
        if (tags_.isEmpty()) {
          tags_ = other.tags_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureTagsIsMutable();
          tags_.addAll(other.tags_);
        }
        onChanged();
      }
      if (other.hasLastModificationTime()) {
        mergeLastModificationTime(other.getLastModificationTime());
      }
      if (!other.getEngineParameter().isEmpty()) {
        engineParameter_ = other.engineParameter_;
        onChanged();
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        onChanged();
      }
      if (!other.rejected_.isEmpty()) {
        if (rejected_.isEmpty()) {
          rejected_ = other.rejected_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureRejectedIsMutable();
          rejected_.addAll(other.rejected_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Situation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Situation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp creationTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> creationTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp creation_time = 2;</code>
     * @return Whether the creationTime field is set.
     */
    public boolean hasCreationTime() {
      return creationTimeBuilder_ != null || creationTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp creation_time = 2;</code>
     * @return The creationTime.
     */
    public com.google.protobuf.Timestamp getCreationTime() {
      if (creationTimeBuilder_ == null) {
        return creationTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : creationTime_;
      } else {
        return creationTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp creation_time = 2;</code>
     */
    public Builder setCreationTime(com.google.protobuf.Timestamp value) {
      if (creationTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        creationTime_ = value;
        onChanged();
      } else {
        creationTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp creation_time = 2;</code>
     */
    public Builder setCreationTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (creationTimeBuilder_ == null) {
        creationTime_ = builderForValue.build();
        onChanged();
      } else {
        creationTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp creation_time = 2;</code>
     */
    public Builder mergeCreationTime(com.google.protobuf.Timestamp value) {
      if (creationTimeBuilder_ == null) {
        if (creationTime_ != null) {
          creationTime_ =
            com.google.protobuf.Timestamp.newBuilder(creationTime_).mergeFrom(value).buildPartial();
        } else {
          creationTime_ = value;
        }
        onChanged();
      } else {
        creationTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp creation_time = 2;</code>
     */
    public Builder clearCreationTime() {
      if (creationTimeBuilder_ == null) {
        creationTime_ = null;
        onChanged();
      } else {
        creationTime_ = null;
        creationTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp creation_time = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreationTimeBuilder() {
      
      onChanged();
      return getCreationTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp creation_time = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreationTimeOrBuilder() {
      if (creationTimeBuilder_ != null) {
        return creationTimeBuilder_.getMessageOrBuilder();
      } else {
        return creationTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : creationTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp creation_time = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreationTimeFieldBuilder() {
      if (creationTimeBuilder_ == null) {
        creationTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreationTime(),
                getParentForChildren(),
                isClean());
        creationTime_ = null;
      }
      return creationTimeBuilder_;
    }

    private AlarmSet alarms_;
    private com.google.protobuf.SingleFieldBuilderV3<
        AlarmSet, AlarmSet.Builder, AlarmSetOrBuilder> alarmsBuilder_;
    /**
     * <code>.AlarmSet alarms = 3;</code>
     * @return Whether the alarms field is set.
     */
    public boolean hasAlarms() {
      return alarmsBuilder_ != null || alarms_ != null;
    }
    /**
     * <code>.AlarmSet alarms = 3;</code>
     * @return The alarms.
     */
    public AlarmSet getAlarms() {
      if (alarmsBuilder_ == null) {
        return alarms_ == null ? AlarmSet.getDefaultInstance() : alarms_;
      } else {
        return alarmsBuilder_.getMessage();
      }
    }
    /**
     * <code>.AlarmSet alarms = 3;</code>
     */
    public Builder setAlarms(AlarmSet value) {
      if (alarmsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        alarms_ = value;
        onChanged();
      } else {
        alarmsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.AlarmSet alarms = 3;</code>
     */
    public Builder setAlarms(
        AlarmSet.Builder builderForValue) {
      if (alarmsBuilder_ == null) {
        alarms_ = builderForValue.build();
        onChanged();
      } else {
        alarmsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.AlarmSet alarms = 3;</code>
     */
    public Builder mergeAlarms(AlarmSet value) {
      if (alarmsBuilder_ == null) {
        if (alarms_ != null) {
          alarms_ =
            AlarmSet.newBuilder(alarms_).mergeFrom(value).buildPartial();
        } else {
          alarms_ = value;
        }
        onChanged();
      } else {
        alarmsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.AlarmSet alarms = 3;</code>
     */
    public Builder clearAlarms() {
      if (alarmsBuilder_ == null) {
        alarms_ = null;
        onChanged();
      } else {
        alarms_ = null;
        alarmsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.AlarmSet alarms = 3;</code>
     */
    public AlarmSet.Builder getAlarmsBuilder() {
      
      onChanged();
      return getAlarmsFieldBuilder().getBuilder();
    }
    /**
     * <code>.AlarmSet alarms = 3;</code>
     */
    public AlarmSetOrBuilder getAlarmsOrBuilder() {
      if (alarmsBuilder_ != null) {
        return alarmsBuilder_.getMessageOrBuilder();
      } else {
        return alarms_ == null ?
            AlarmSet.getDefaultInstance() : alarms_;
      }
    }
    /**
     * <code>.AlarmSet alarms = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        AlarmSet, AlarmSet.Builder, AlarmSetOrBuilder>
        getAlarmsFieldBuilder() {
      if (alarmsBuilder_ == null) {
        alarmsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            AlarmSet, AlarmSet.Builder, AlarmSetOrBuilder>(
                getAlarms(),
                getParentForChildren(),
                isClean());
        alarms_ = null;
      }
      return alarmsBuilder_;
    }

    private Object severity_ = "";
    /**
     * <code>string severity = 4;</code>
     * @return The severity.
     */
    public String getSeverity() {
      Object ref = severity_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        severity_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string severity = 4;</code>
     * @return The bytes for severity.
     */
    public com.google.protobuf.ByteString
        getSeverityBytes() {
      Object ref = severity_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        severity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string severity = 4;</code>
     * @param value The severity to set.
     * @return This builder for chaining.
     */
    public Builder setSeverity(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      severity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string severity = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeverity() {
      
      severity_ = getDefaultInstance().getSeverity();
      onChanged();
      return this;
    }
    /**
     * <code>string severity = 4;</code>
     * @param value The bytes for severity to set.
     * @return This builder for chaining.
     */
    public Builder setSeverityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      severity_ = value;
      onChanged();
      return this;
    }

    private Object diagnostic_ = "";
    /**
     * <code>string diagnostic = 5;</code>
     * @return The diagnostic.
     */
    public String getDiagnostic() {
      Object ref = diagnostic_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        diagnostic_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string diagnostic = 5;</code>
     * @return The bytes for diagnostic.
     */
    public com.google.protobuf.ByteString
        getDiagnosticBytes() {
      Object ref = diagnostic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        diagnostic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string diagnostic = 5;</code>
     * @param value The diagnostic to set.
     * @return This builder for chaining.
     */
    public Builder setDiagnostic(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      diagnostic_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string diagnostic = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDiagnostic() {
      
      diagnostic_ = getDefaultInstance().getDiagnostic();
      onChanged();
      return this;
    }
    /**
     * <code>string diagnostic = 5;</code>
     * @param value The bytes for diagnostic to set.
     * @return This builder for chaining.
     */
    public Builder setDiagnosticBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      diagnostic_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTagsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        tags_ = new com.google.protobuf.LazyStringArrayList(tags_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string tags = 6;</code>
     * @return A list containing the tags.
     */
    public com.google.protobuf.ProtocolStringList
        getTagsList() {
      return tags_.getUnmodifiableView();
    }
    /**
     * <code>repeated string tags = 6;</code>
     * @return The count of tags.
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <code>repeated string tags = 6;</code>
     * @param index The index of the element to return.
     * @return The tags at the given index.
     */
    public String getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <code>repeated string tags = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the tags at the given index.
     */
    public com.google.protobuf.ByteString
        getTagsBytes(int index) {
      return tags_.getByteString(index);
    }
    /**
     * <code>repeated string tags = 6;</code>
     * @param index The index to set the value at.
     * @param value The tags to set.
     * @return This builder for chaining.
     */
    public Builder setTags(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
      tags_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tags = 6;</code>
     * @param value The tags to add.
     * @return This builder for chaining.
     */
    public Builder addTags(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
      tags_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tags = 6;</code>
     * @param values The tags to add.
     * @return This builder for chaining.
     */
    public Builder addAllTags(
        Iterable<String> values) {
      ensureTagsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tags_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tags = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTags() {
      tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tags = 6;</code>
     * @param value The bytes of the tags to add.
     * @return This builder for chaining.
     */
    public Builder addTagsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureTagsIsMutable();
      tags_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp lastModificationTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastModificationTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp last_modification_time = 7;</code>
     * @return Whether the lastModificationTime field is set.
     */
    public boolean hasLastModificationTime() {
      return lastModificationTimeBuilder_ != null || lastModificationTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp last_modification_time = 7;</code>
     * @return The lastModificationTime.
     */
    public com.google.protobuf.Timestamp getLastModificationTime() {
      if (lastModificationTimeBuilder_ == null) {
        return lastModificationTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastModificationTime_;
      } else {
        return lastModificationTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp last_modification_time = 7;</code>
     */
    public Builder setLastModificationTime(com.google.protobuf.Timestamp value) {
      if (lastModificationTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastModificationTime_ = value;
        onChanged();
      } else {
        lastModificationTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_modification_time = 7;</code>
     */
    public Builder setLastModificationTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (lastModificationTimeBuilder_ == null) {
        lastModificationTime_ = builderForValue.build();
        onChanged();
      } else {
        lastModificationTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_modification_time = 7;</code>
     */
    public Builder mergeLastModificationTime(com.google.protobuf.Timestamp value) {
      if (lastModificationTimeBuilder_ == null) {
        if (lastModificationTime_ != null) {
          lastModificationTime_ =
            com.google.protobuf.Timestamp.newBuilder(lastModificationTime_).mergeFrom(value).buildPartial();
        } else {
          lastModificationTime_ = value;
        }
        onChanged();
      } else {
        lastModificationTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_modification_time = 7;</code>
     */
    public Builder clearLastModificationTime() {
      if (lastModificationTimeBuilder_ == null) {
        lastModificationTime_ = null;
        onChanged();
      } else {
        lastModificationTime_ = null;
        lastModificationTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_modification_time = 7;</code>
     */
    public com.google.protobuf.Timestamp.Builder getLastModificationTimeBuilder() {
      
      onChanged();
      return getLastModificationTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp last_modification_time = 7;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getLastModificationTimeOrBuilder() {
      if (lastModificationTimeBuilder_ != null) {
        return lastModificationTimeBuilder_.getMessageOrBuilder();
      } else {
        return lastModificationTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : lastModificationTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp last_modification_time = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getLastModificationTimeFieldBuilder() {
      if (lastModificationTimeBuilder_ == null) {
        lastModificationTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getLastModificationTime(),
                getParentForChildren(),
                isClean());
        lastModificationTime_ = null;
      }
      return lastModificationTimeBuilder_;
    }

    private Object engineParameter_ = "";
    /**
     * <code>string engine_parameter = 8;</code>
     * @return The engineParameter.
     */
    public String getEngineParameter() {
      Object ref = engineParameter_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        engineParameter_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string engine_parameter = 8;</code>
     * @return The bytes for engineParameter.
     */
    public com.google.protobuf.ByteString
        getEngineParameterBytes() {
      Object ref = engineParameter_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        engineParameter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string engine_parameter = 8;</code>
     * @param value The engineParameter to set.
     * @return This builder for chaining.
     */
    public Builder setEngineParameter(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      engineParameter_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string engine_parameter = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearEngineParameter() {
      
      engineParameter_ = getDefaultInstance().getEngineParameter();
      onChanged();
      return this;
    }
    /**
     * <code>string engine_parameter = 8;</code>
     * @param value The bytes for engineParameter to set.
     * @return This builder for chaining.
     */
    public Builder setEngineParameterBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      engineParameter_ = value;
      onChanged();
      return this;
    }

    private Object status_ = "";
    /**
     * <code>string status = 9;</code>
     * @return The status.
     */
    public String getStatus() {
      Object ref = status_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string status = 9;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 9;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string status = 9;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      status_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList rejected_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureRejectedIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        rejected_ = new com.google.protobuf.LazyStringArrayList(rejected_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string rejected = 10;</code>
     * @return A list containing the rejected.
     */
    public com.google.protobuf.ProtocolStringList
        getRejectedList() {
      return rejected_.getUnmodifiableView();
    }
    /**
     * <code>repeated string rejected = 10;</code>
     * @return The count of rejected.
     */
    public int getRejectedCount() {
      return rejected_.size();
    }
    /**
     * <code>repeated string rejected = 10;</code>
     * @param index The index of the element to return.
     * @return The rejected at the given index.
     */
    public String getRejected(int index) {
      return rejected_.get(index);
    }
    /**
     * <code>repeated string rejected = 10;</code>
     * @param index The index of the value to return.
     * @return The bytes of the rejected at the given index.
     */
    public com.google.protobuf.ByteString
        getRejectedBytes(int index) {
      return rejected_.getByteString(index);
    }
    /**
     * <code>repeated string rejected = 10;</code>
     * @param index The index to set the value at.
     * @param value The rejected to set.
     * @return This builder for chaining.
     */
    public Builder setRejected(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRejectedIsMutable();
      rejected_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string rejected = 10;</code>
     * @param value The rejected to add.
     * @return This builder for chaining.
     */
    public Builder addRejected(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRejectedIsMutable();
      rejected_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string rejected = 10;</code>
     * @param values The rejected to add.
     * @return This builder for chaining.
     */
    public Builder addAllRejected(
        Iterable<String> values) {
      ensureRejectedIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, rejected_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string rejected = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearRejected() {
      rejected_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string rejected = 10;</code>
     * @param value The bytes of the rejected to add.
     * @return This builder for chaining.
     */
    public Builder addRejectedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureRejectedIsMutable();
      rejected_.add(value);
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Situation)
  }

  // @@protoc_insertion_point(class_scope:Situation)
  private static final Situation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Situation();
  }

  public static Situation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Situation>
      PARSER = new com.google.protobuf.AbstractParser<Situation>() {
    @Override
    public Situation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Situation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Situation> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Situation> getParserForType() {
    return PARSER;
  }

  @Override
  public Situation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

