// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: situationset.proto

package org.opennms.alec.grpc;

public interface SituationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Situation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.google.protobuf.Timestamp creation_time = 2;</code>
   * @return Whether the creationTime field is set.
   */
  boolean hasCreationTime();
  /**
   * <code>.google.protobuf.Timestamp creation_time = 2;</code>
   * @return The creationTime.
   */
  com.google.protobuf.Timestamp getCreationTime();
  /**
   * <code>.google.protobuf.Timestamp creation_time = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreationTimeOrBuilder();

  /**
   * <code>.AlarmSet alarms = 3;</code>
   * @return Whether the alarms field is set.
   */
  boolean hasAlarms();
  /**
   * <code>.AlarmSet alarms = 3;</code>
   * @return The alarms.
   */
  AlarmSet getAlarms();
  /**
   * <code>.AlarmSet alarms = 3;</code>
   */
  AlarmSetOrBuilder getAlarmsOrBuilder();

  /**
   * <code>string severity = 4;</code>
   * @return The severity.
   */
  String getSeverity();
  /**
   * <code>string severity = 4;</code>
   * @return The bytes for severity.
   */
  com.google.protobuf.ByteString
      getSeverityBytes();

  /**
   * <code>string diagnostic = 5;</code>
   * @return The diagnostic.
   */
  String getDiagnostic();
  /**
   * <code>string diagnostic = 5;</code>
   * @return The bytes for diagnostic.
   */
  com.google.protobuf.ByteString
      getDiagnosticBytes();

  /**
   * <code>repeated string tags = 6;</code>
   * @return A list containing the tags.
   */
  java.util.List<String>
      getTagsList();
  /**
   * <code>repeated string tags = 6;</code>
   * @return The count of tags.
   */
  int getTagsCount();
  /**
   * <code>repeated string tags = 6;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  String getTags(int index);
  /**
   * <code>repeated string tags = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);

  /**
   * <code>.google.protobuf.Timestamp last_modification_time = 7;</code>
   * @return Whether the lastModificationTime field is set.
   */
  boolean hasLastModificationTime();
  /**
   * <code>.google.protobuf.Timestamp last_modification_time = 7;</code>
   * @return The lastModificationTime.
   */
  com.google.protobuf.Timestamp getLastModificationTime();
  /**
   * <code>.google.protobuf.Timestamp last_modification_time = 7;</code>
   */
  com.google.protobuf.TimestampOrBuilder getLastModificationTimeOrBuilder();

  /**
   * <code>string engine_parameter = 8;</code>
   * @return The engineParameter.
   */
  String getEngineParameter();
  /**
   * <code>string engine_parameter = 8;</code>
   * @return The bytes for engineParameter.
   */
  com.google.protobuf.ByteString
      getEngineParameterBytes();

  /**
   * <code>string status = 9;</code>
   * @return The status.
   */
  String getStatus();
  /**
   * <code>string status = 9;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>repeated string rejected = 10;</code>
   * @return A list containing the rejected.
   */
  java.util.List<String>
      getRejectedList();
  /**
   * <code>repeated string rejected = 10;</code>
   * @return The count of rejected.
   */
  int getRejectedCount();
  /**
   * <code>repeated string rejected = 10;</code>
   * @param index The index of the element to return.
   * @return The rejected at the given index.
   */
  String getRejected(int index);
  /**
   * <code>repeated string rejected = 10;</code>
   * @param index The index of the value to return.
   * @return The bytes of the rejected at the given index.
   */
  com.google.protobuf.ByteString
      getRejectedBytes(int index);
}
