= Pre-Installation Tasks
:imagesdir: ../assets/images

This section describes the tasks you must complete before installing ALEC.
These tasks include configuring OpenNMS and setting up an APT or YUM repository.

== OpenNMS configuration

=== $OPENNMS_HOME

The ALEC installation instructions refer to the `$OPENNMS_HOME` environment variable, which must be set.

With OpenNMS running on RHEL or CentOS, this is commonly set as:

```
export OPENNMS_HOME=/opt/opennms
```

With OpenNMS running on Ubuntu or Debian, this is commonly set as:

```
export OPENNMS_HOME=/usr/share/opennms
```

 ## need to verify what all this does. It's very confusing.##

=== Run a health check

You can use the `health:check` command in the Karaf shell to help validate your deployment.

From the OpenNMS Karaf shell, run the following:

```
health:check
```
You will probably see something similar to the following, since the `opennms-flows` feature is installed by default:

```
admin@opennms> health:check
Verifying the health of the container

Verifying installed bundles                    [ Success  ]
Connecting to ElasticSearch ReST API (Flows)   [ Timeout  ] => Health Check did not finish within 5000 ms

=> Oh no, something is wrong
```
The health check fails, since no Elasticsearch server is configured.
You can either uninstall the feature (using `feature:uninstall opennms-flows`), or point the feature to an Elasticsearch instance:

```
config:edit org.opennms.features.flows.persistence.elastic
config:property-set elasticUrl http://elastic:9200
config:update
```
TIP: Replace the sample URL with one that points to your Elasticsearch instance.

Run the health check again, and expect to see output similar to the following:

```
admin@opennms> health:check
Verifying the health of the container

Verifying installed bundles                    [ Success  ]
Connecting to ElasticSearch ReST API (Flows)   [ Success  ]

=> Everything is awesome
```

Everything is awesome.

=== Enable alarm history storage for Elasticsearch

When using ALEC, we strongly recommend that you leverage our integration for maintaining alarm history in Elasticsearch.
ALEC can use this data for analysis and to help train the correlation engine.

.From the OpenNMS Karaf shell, run the following, replacing the sample URL with one that points to your Elasticsearch instance:

```
config:edit org.opennms.features.alarms.history.elastic
config:property-set elasticUrl http://elastic:9200
config:update
```

.Use the following to install the feature:
```
feature:install opennms-alarm-history-elastic
```

If everything is configured properly, the health check should show output similar to the following:
```
admin@opennms> health:check
Verifying the health of the container

Verifying installed bundles                                       [ Success  ]
Connecting to ElasticSearch ReST API (Flows)                      [ Success  ]
Number of active alarms stored in Elasticsearch (Alarm History)   [ Success  ] => Found 0 alarms.

=> Everything is awesome
```

=== Enable Syslogd

Enabling Syslogd lets you take advantage of the Syslog patterns and event definitions that ALEC provides.

Enable Syslogd by editing `$OPENNMS_HOME/etc/service-configuration.xml` and changing the following:

```
<service enabled="false">
    <name>OpenNMS:Name=Syslogd</name>
```

to:

```
<service>
    <name>OpenNMS:Name=Syslogd</name>
```

This change will come into effect the next time OpenNMS restarts.
Do not restart OpenNMS at this point.

== ALEC/OpenNMS package repositories

Packages for ALEC are made available the same Debian and YUM repositories as OpenNMS.
If you already have the stable repository installed, you can skip this step.

=== Set up APT repository (Ubuntu/Debian)

For Ubuntu- or Debian-based distributions, install the repository:

```
cat << EOF | sudo tee /etc/apt/sources.list.d/opennms.list
deb https://debian.opennms.org stable main
deb-src https://debian.opennms.org stable main
EOF
wget -O - https://debian.opennms.org/OPENNMS-GPG-KEY | apt-key add -
apt update
```

=== Set up YUM repository (RHEL/CentOS)

For RHEL- or CentOS-based distributions, install the repository:

```
yum -y install https://yum.opennms.org/repofiles/opennms-repo-stable-rhel7.noarch.rpm
rpm --import https://yum.opennms.org/OPENNMS-GPG-KEY
```
